### ISSUE TITLE
Issues for tracking progress.

### ISSUE THREAD

**Issue by JeroenCops** [JeroenCops/LearningRust#1]
# TO DO

- [x] Introductie
- [x] Laten we ermee beginnen
- [x] Zelfstudie: Raadspel
- [x] Syntax en Semantiek
    - [x] Variable bindingen
    - [x] Functies
    - [x] Primitieve types
    - [x] Commentaar
    - [x] if
    - [x] Lussen
    - [x] Vectoren
    - [ ] Bezit
    - [ ] Referenties en lenen
    - [ ] Levensduur
    - [ ] Muteerbaarheid
    - [ ] Structuur
    - [ ] Opsomming
    - [ ] Schikken
    - [ ] Patronen
    - [ ] Methode syntax
    - [ ] Strings
    - [ ] Genericiteit
    - [ ] Kenmerken
    - [ ] Drop
    - [ ] if let
    - [ ] Kenmerk Objecten
    - [ ] Closure
    - [ ] Universele Functie Oproep Syntax
    - [ ] Kratten en Modules
    - [ ] `const` en `static`
    - [ ] Attributen
    - [ ] `type` aliassen
    - [ ] Casten tussen types
    - [ ] Geassocieerde types
    - [ ] Ongebonden types
    - [ ] Operatoren en overbelasten
    - [ ] Dereferentie coercions
    - [ ] Macros
    - [ ] Ruwe Pointers
    - [ ] `unsafe`
- [ ] Effectieve Rust
    - [ ] De stack en de Heap
    - [ ] Testen
    - [ ] Geconditioneerde Compilatie
    - [ ] Documentatie
    - [ ] Iterators
    - [ ] Concurrency
    - [ ] Errors Hanteren
    - [ ] Jouw garanties kiezen
    - [ ] FFI
    - [ ] Borrow en AsRef
    - [ ] Publicatie Kanalen
    - [ ] Rust gebruiken zonder de standaard bibliotheek
- [ ] Nightly Rust
    - [ ] Compiler Plugins
    - [ ] Inline Assembleertaal
    - [ ] Geen stdlib
    - [ ] Intrinsics
    - [ ] Taal items
    - [ ] Geavanceerd linken
    - [ ] Benchmark Testen
    - [ ] Box Syntax en Patronen
    - [ ] Patroon Snedes
    - [ ] Geassocieerde Constanten
    - [ ] Aangepaste Allocatoren
- [ ] Woordenlijst
- [ ] Syntax Catalogus
- [ ] Bibliografie
